apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubecommander
  namespace: kubedial
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubecommander
  namespace: kubedial
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubecommander
  namespace: kubedial
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubecommander
subjects:
  - kind: ServiceAccount
    name: kubecommander
    namespace: kubedial
